### ISSUE TITLE
puppetserver 7.x's logged message about hiera() deprecation includes a broken URL

### ISSUE THREAD

**Issue by timmooney** [puppetlabs/puppetserver#2835]
## Describe the Bug
puppetserver 7.16 logs a deprecation warning with a broken URL:

`2024-03-11T17:43:29.958-05:00 WARN  [qtp1601237113-43] [puppetserver] Puppet The function 'hiera' is deprecated in favor of using 'lookup'. See https://puppet.com/docs/puppet/7.29/deprecated_language.html
   (file & line not available)
`

## Expected Behavior
It's very handy that the puppetserver produces a log message with a "go here to learn more" URL.  The only thing that needs to change is for the URL it logs to be updated for the current location.

## Steps to Reproduce
1.  Use hiera() instead of lookup() somewhere in your puppet code
2. restart puppetserver on your puppet server.
3. Do a 'no-op' puppet agent run
4. browse the /var/log/puppetlabs/puppsetserver/puppetserver.log
5. copy the URL and paste it into a browser
6. puppet.com's custom 404 page comes up

## Environment
 - Version: puppetserver 7.16.0, puppet-agent 7.29.1
 - Platform: RHEL 9.x

**Comment by justinstoller** [comment]
Thanks for reporting this! I've looked a bit into it and found the warning is coming from the Puppet code base itself. I've opened a related ticket here that you can track its progress https://github.com/puppetlabs/puppet/issues/9378
