### ISSUE TITLE
Puppetserver classloader errors since 8.6.1

### ISSUE THREAD

**Issue by LBlaboon** [puppetlabs/puppetserver#2869]
## Describe the Bug
Starting with 8.6.1, when I try to start puppetserver it immediately crashes with the following error in the logs:
`Execution error (UnsatisfiedLinkError) at jdk.internal.loader.NativeLibraries/loadLibrary (REPL:-1).`
`Native Library /usr/lib/libfacter.so.3.14.24 already loaded in another classloader`

Downgrading back to 8.6.0 resolves the issue.

## Expected Behavior
The service starts and remains running.

## Steps to Reproduce
1. Upgrade puppetserver to 8.6.1 (or any later version) from 8.6.0
2. Start the service

## Environment
 - Archlinux
 - Puppetserver 8.6.1 and 8.6.2
 - Normally JRE 22, but also tried JRE 11 and 17 with the same results
 - JRuby 9.4.x

## Additional Context
I noticed that 8.6.1 adds parallelization of JRuby workers. I tried setting `jruby-puppet.instance-creation-concurrency` to 1 in puppetserver.conf to disable that behavior, but the same issue persists. `max-active-instances` is currently set to 3.

I have attached the clojure crash report for further reference.
[clojure-5866015620741618811.txt](https://github.com/user-attachments/files/16384368/clojure-5866015620741618811.txt)

**Comment by joshcooper** [comment]
libfacter.so shouldn't be getting loaded. That's was only necessary in puppetserver 6, before facter 4 was rewritten in ruby. For example see https://github.com/puppetlabs/puppetserver/pull/2829 Can you search for `facter.jar` to see if it's being added to the java classpath?

**Comment by LBlaboon** [comment]
I can't find anywhere obvious where `facter.jar` is being added to the classpath. The only path that puppetserver appears to be adding is `/opt/puppetlabs/server/data/puppetserver/jars/`, which is empty on my system. The version of facter that is supplied by Arch is quite old (3.14.24) and does include `facter.jar` in my system's vendor_ruby directory. I've tried deleting that file and also manually upgrading to the latest version of facter (without `facter.jar`) but in both cases puppetserver fails to start with a JRuby exception that it can't load facter (even though `facter` itself is completely usable standalone, and `puppet` seems to have no trouble applying catalogs).

**Comment by LBlaboon** [comment]
Closing this, as since my original report Arch has updated all their puppet-related packages to the latest and I have updated my `ruby-load-path` to reflect the new location of facter's libraries, thus resolving the issue.
